"""Offline design only. Runtime C simulation does not import this module."""
import argparse
import hashlib
import json
from dataclasses import asdict
from pathlib import Path
import numpy as np
from scipy.linalg import expm, solve_discrete_are
from config.robot_params import PARAMS, Q_DIAG, R_VALUE
from simulation.model import continuous_matrices

ROOT = Path(__file__).resolve().parents[1]


def discretize(a, b, dt):
    # exp([[A,B],[0,0]]*Ts) = [[Ad,Bd],[0,I]]; valid even when A is singular.
    n, m = b.shape
    block = np.zeros((n+m, n+m))
    block[:n, :n], block[:n, n:] = a, b
    zoh = expm(block * dt)
    return zoh[:n, :n], zoh[:n, n:]


def riccati_iteration(ad, bd, q, r, tolerance=1e-12, max_iterations=200000):
    p = q.copy()
    for iteration in range(1, max_iterations+1):
        k = np.linalg.solve(r + bd.T @ p @ bd, bd.T @ p @ ad)
        next_p = q + ad.T @ p @ ad - ad.T @ p @ bd @ k
        next_p = (next_p + next_p.T)/2
        error = np.linalg.norm(next_p-p, 'fro') / max(1.0, np.linalg.norm(next_p, 'fro'))
        p = next_p
        if error < tolerance:
            return p, iteration
    raise RuntimeError('Riccati iteration did not converge; check model and weights.')


def design(q_diag=Q_DIAG, r_value=R_VALUE):
    weights = np.asarray(q_diag, dtype=float)
    if weights.shape != (4,) or not np.all(np.isfinite(weights)) or np.any(weights <= 0):
        raise ValueError('This first version requires four finite positive Q weights.')
    if not np.isfinite(r_value) or r_value <= 0:
        raise ValueError('R must be finite and positive.')
    a, b = continuous_matrices()
    ad, bd = discretize(a, b, PARAMS.sample_time)
    q, r = np.diag(weights), np.array([[r_value]])
    p, iterations = riccati_iteration(ad, bd, q, r)
    k = np.linalg.solve(r + bd.T @ p @ bd, bd.T @ p @ ad)
    reference_p = solve_discrete_are(ad, bd, q, r)
    np.testing.assert_allclose(p, reference_p, rtol=1e-7, atol=1e-5)
    residual = ad.T@p@ad-p-ad.T@p@bd@k+q
    relative_residual = np.linalg.norm(residual)/np.linalg.norm(p)
    eigenvalues = np.linalg.eigvals(ad-bd@k)
    if np.max(np.abs(eigenvalues)) >= 1 or relative_residual > 1e-10:
        raise RuntimeError('LQR stability or DARE residual check failed.')
    for name, value in [('A', a), ('B', b), ('Ad', ad), ('Bd', bd), ('Q', q), ('R', r), ('P', p), ('K', k)]:
        print(f'{name} =\n{value}')
    print('closed-loop eigenvalues =', eigenvalues)
    print(f'Riccati iterations = {iterations}; relative residual = {relative_residual:.3e}')
    print('PASS: SciPy agreement; all closed-loop eigenvalues inside unit circle.')
    data = {name: value.tolist() for name, value in [('A', a), ('B', b), ('Ad', ad), ('Bd', bd), ('Q', q), ('R', r), ('P', p), ('K', k)]}
    data.update(params=asdict(PARAMS), iterations=iterations, relative_residual=relative_residual,
                eigenvalues=[[v.real, v.imag] for v in eigenvalues])
    data['design_id'] = hashlib.sha256(json.dumps(data, sort_keys=True).encode()).hexdigest()
    return data


def export(data):
    destination = ROOT / 'config' / 'lqr_design.json'
    destination.write_text(json.dumps(data, indent=2) + '\n', encoding='utf-8')
    def c_float(value):
        return f'{value:.9e}f'
    gains = ', '.join(c_float(v) for v in data['K'][0])
    header = ('/* Generated by python -m simulation.design_lqr. Rebuild after changes. */\n'
              '#ifndef LQR_GAINS_H\n#define LQR_GAINS_H\n'
              f'#define LQR_DEFAULT_K {{{gains}}}\n'
              f'#define LQR_OUTPUT_LIMIT {c_float(PARAMS.output_limit)}\n'
              f'#define LQR_SAMPLE_TIME {c_float(PARAMS.sample_time)}\n'
              f'#define LQR_DESIGN_ID "{data["design_id"]}"\n#endif\n')
    (ROOT / 'controller').mkdir(exist_ok=True)
    (ROOT / 'controller' / 'lqr_gains.h').write_text(header, encoding='utf-8')
    print('Exported config/lqr_design.json and controller/lqr_gains.h')


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--q', nargs=4, type=float, default=Q_DIAG, metavar=('POS','VEL','PITCH','RATE'))
    parser.add_argument('--r', type=float, default=R_VALUE)
    args = parser.parse_args()
    np.set_printoptions(precision=9, suppress=True)
    export(design(args.q, args.r))
