"""Create an independently buildable, dependency-audited controller package."""
from __future__ import annotations
import hashlib
import json
import re
import shutil
import subprocess
from datetime import datetime, timezone
from pathlib import Path
import numpy as np
from simulation.chassis_sim import ROOT


DEFAULT_LQR=np.array([
[-580.793983,783.731877,-401.575832,19.616999],[-103.178699,131.034870,-62.460267,2.731318],
[-155.590732,183.885801,-81.428101,6.009046],[-341.501129,397.130252,-172.488632,12.079763],
[119.223616,-57.918692,-34.154865,25.772479],[53.306674,-38.632670,1.134225,4.621841],
[4690.692116,-4403.513912,1248.250795,-33.449125],[855.103215,-779.177375,211.010110,-4.502903],
[781.538570,-710.924039,187.640098,-.134923],[1666.326930,-1506.230392,393.445801,.396554],
[367.630338,-548.112480,296.870504,22.952638],[-27.139692,-27.952625,40.408410,2.863716]])
DEFAULT_MPC=np.array([
[-27.271530,70.405511,-33.976441,1.450837],[-42.809756,104.613820,-59.051571,3.041969],
[-.012390,.020052,-.010703,.001542],[4.085050,6.560460,-8.012157,1.573399],
[2.017577,-1.380650,.122355,.058932],[32.634487,-27.430700,5.341886,.514025],
[398.732249,-404.340647,113.899198,-2.071685],[834.653329,-827.303228,246.558758,-8.398013],
[.125928,-.120813,.033687,-.000149],[72.468718,-79.093454,24.370378,.553580],
[3.366239,-5.444027,2.880210,-.078041],[-10.879463,-17.219974,21.690707,-.201016]])
DEFAULT_PARAMETERS=dict(sample_time_s=.001,thigh_length_m=.135,calf_length_m=.24,joint_distance_m=.12,wheel_distance_m=.52,
                        body_mass_kg=7.645,max_acceleration_m_s2=2.5,airborne_force_n=20.,wheel_torque_limit_nm=8.,
                        joint_torque_limit_nm=35.,min_leg_length_m=.15,max_leg_length_m=.33,leg_topology=0)


def _identifier(text):
    value=re.sub(r'[^A-Za-z0-9_.-]+','-',text.strip()).strip('-')
    if not value:raise ValueError('配置名称不能为空')
    return value[:64]


def _c_float(value):
    text=f'{float(value):.9g}'
    if 'e' not in text.lower() and '.' not in text:text+='.0'
    return text+'f'


def _array(name,value):
    rows=',\n'.join('    {'+', '.join(_c_float(v) for v in row)+'}' for row in value)
    return f'static const float {name}[12][4] = {{\n{rows}\n}};'


def generated_header(profile,lqr,mpc,p):
    return f'''/* Generated by WheelLeg production exporter. Do not edit by hand. */
#ifndef WLC_GENERATED_PARAMS_H
#define WLC_GENERATED_PARAMS_H
#define WLC_GENERATED_PROFILE "{profile}"
#define WLC_GENERATED_SAMPLE_TIME_S {_c_float(p['sample_time_s'])}
#define WLC_GENERATED_PARAMETER_VERSION 1u
#define WLC_GENERATED_THIGH_LENGTH_M {_c_float(p['thigh_length_m'])}
#define WLC_GENERATED_CALF_LENGTH_M {_c_float(p['calf_length_m'])}
#define WLC_GENERATED_JOINT_DISTANCE_M {_c_float(p['joint_distance_m'])}
#define WLC_GENERATED_WHEEL_DISTANCE_M {_c_float(p['wheel_distance_m'])}
#define WLC_GENERATED_BODY_MASS_KG {_c_float(p['body_mass_kg'])}
#define WLC_GENERATED_MAX_ACCELERATION_M_S2 {_c_float(p['max_acceleration_m_s2'])}
#define WLC_GENERATED_AIRBORNE_FORCE_N {_c_float(p['airborne_force_n'])}
#define WLC_GENERATED_WHEEL_TORQUE_LIMIT_NM {_c_float(p['wheel_torque_limit_nm'])}
#define WLC_GENERATED_JOINT_TORQUE_LIMIT_NM {_c_float(p['joint_torque_limit_nm'])}
#define WLC_GENERATED_MIN_LEG_LENGTH_M {_c_float(p['min_leg_length_m'])}
#define WLC_GENERATED_MAX_LEG_LENGTH_M {_c_float(p['max_leg_length_m'])}
{_array('WLC_GENERATED_LQR',lqr)}
{_array('WLC_GENERATED_MPC',mpc)}
#endif
'''


TEST_RUNNER=r'''#include "wheel_leg.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
typedef struct { int calls; } ExternalPID;
static float external_pid_calculate(void *instance,float measure,float reference) {
    ExternalPID *pid=(ExternalPID *)instance;pid->calls++;return reference-measure;
}
static void external_pid_reset(void *instance) { ((ExternalPID *)instance)->calls=0; }
int main(void) {
    int tick,motor;ExternalPID external_pid;wheel_leg_initialize();
    assert(wheel_leg_bind_pid(0u,&external_pid,external_pid_calculate,external_pid_reset)==0);
    assert(wheel_leg_call_pid(0u,2.0f,5.0f)==3.0f&&external_pid.calls==1);
    @JOINT_INITIALIZATION@
    wheel_leg_U.normal_force_n[0]=wheel_leg_U.normal_force_n[1]=80.0f;
    wheel_leg_U.leg_length_command_m=.18f;
    for(tick=0;tick<3000;++tick) {
        wheel_leg_U.time_s=tick*wheel_leg_P.core.sample_time_s;wheel_leg_U.velocity_command_m_s=tick>500?.4f:0.0f;
        wheel_leg_step();
        for(motor=0;motor<2;++motor)assert(isfinite(wheel_leg_Y.wheel_torque_nm[motor])&&fabsf(wheel_leg_Y.wheel_torque_nm[motor])<=wheel_leg_P.core.wheel_torque_limit_nm);
        for(motor=0;motor<4;++motor)assert(isfinite(wheel_leg_Y.joint_torque_nm[motor])&&fabsf(wheel_leg_Y.joint_torque_nm[motor])<=wheel_leg_P.core.joint_torque_limit_nm);
    }
    assert(external_pid.calls>3000); /* Port 0 is called by the left leg length loop. */
    wheel_leg_U.zero_force_command=1u;wheel_leg_step();
    for(motor=0;motor<2;++motor)assert(wheel_leg_Y.wheel_torque_nm[motor]==0.0f);
    for(motor=0;motor<4;++motor)assert(wheel_leg_Y.joint_torque_nm[motor]==0.0f);
    printf("PASS wheel_leg lifecycle + external PID interface; DW=%u bytes\n",(unsigned)sizeof(DW_wheel_leg_T));wheel_leg_terminate();
    return 0;
}
'''

BAREMETAL=r'''/* Call from a hardware timer at wheel_leg_P.core.sample_time_s. */
#include "wheel_leg.h"
void Control_Init(void) { wheel_leg_initialize(); }
void Control_1kHz(void) {
    /* TODO: write calibrated sensors and commands to wheel_leg_U. */
    wheel_leg_step();
    /* TODO: convert six wheel_leg_Y torque values to motor currents. */
    /* Check wheel_leg_Y.status_flags and apply the independent watchdog. */
}
'''

FREERTOS=r'''/* RTOS adapter sketch; the portable core itself has no RTOS dependency. */
#include "wheel_leg.h"
void WheelLegControlTask(void *argument) {
    (void)argument;wheel_leg_initialize();
    for(;;) {
        /* Wait for the exact periodic release, fill wheel_leg_U, call step. */
        wheel_leg_step();
        /* Send wheel_leg_Y through the project's motor driver. */
    }
}
'''

README='''# Wheel-leg generated control model

The public layout follows MATLAB/Simulink Coder conventions: write `wheel_leg_U`,
call `wheel_leg_step()`, then read `wheel_leg_Y`. Intermediate block signals are
in `wheel_leg_B`, discrete/PID states in `wheel_leg_DW`, and tunable parameters
in `wheel_leg_P`.

The generated model does not implement or own a PID algorithm. Bind the application's
existing PID structure and calculate function through `wheel_leg_bind_pid()`, then
call it from `src/wheel_leg_user.c`. Thus advanced filtering, DWT timing, anti-windup
and error handling remain in the application's own PID implementation. User files
are preserved when exporting again.

Integration contract:

1. Call `wheel_leg_initialize()` once.
2. Calibrate sensors into `wheel_leg_U` using SI units and documented signs.
3. Call `wheel_leg_step()` exactly once per configured sample period.
4. Convert `wheel_leg_Y` torque in Nm to motor current in the hardware adapter.
5. Independently implement watchdog, physical emergency stop and board protection.

Build the independent self-test:

```sh
gcc -std=c11 -O2 -Wall -Wextra -Werror -pedantic -Iinclude -Igenerated src/*.c tests/test_runner.c -lm -o wheel_leg_test
./wheel_leg_test
```

The package deliberately contains no HAL, RTOS, CAN, MuJoCo or Python dependency.
Passing the self-test does not authorize high-power operation; follow staged motor,
single-leg, restraint-frame and low-torque commissioning.
'''

INTEGRATION_GUIDE_CN='''# 轮腿控制生成代码接入与自定义 PID 指南

## 1. 文件职责

| 文件 | 作用 | 是否建议修改 |
|---|---|---|
| `include/wheel_leg.h` | 模型公开入口，声明 U/Y/B/DW/P 和三个生命周期函数 | 否 |
| `include/wheel_leg_types.h` | 输入、输出、中间信号、状态和参数结构 | 通常不改 |
| `include/wheel_leg_user_types.h` | 外部 PID 端口和用户自定义存储 | 可以，重复导出会保留 |
| `include/wheel_leg_pid_interface.h` | 外部 PID 函数签名，不包含 PID 算法 | 否 |
| `src/wheel_leg.c` | `initialize/step/terminate` 顶层调度 | 否 |
| `src/wheel_leg_user.c` | 用户控制插入点 | 可以，重复导出会保留 |
| `src/wlc_internal.c` | 当前腿型的 LQR/VMC 与状态机数值核心 | 不建议修改 |
| `src/wlc_kinematics.h` | 当前腿型独立运动学；包内只有这一份实现 | 不建议修改 |
| `generated/wlc_generated_params.h` | UI 生成的质量、几何、限幅和增益 | 不要手改，重新导出 |

## 2. 最小调用顺序

初始化只调用一次：

```c
#include "wheel_leg.h"

void ChassisControlInit(void)
{
    wheel_leg_initialize();
}
```

固定控制周期内，例如 1 kHz 定时器或 RTOS 任务：

```c
void ChassisControl1kHz(void)
{
    /* 1. 将实车传感器填入模型输入，全部使用 SI 单位。 */
    wheel_leg_U.pitch_rad          = imu_pitch_rad;
    wheel_leg_U.pitch_rate_rad_s   = gyro_pitch_rad_s;
    wheel_leg_U.roll_rad           = imu_roll_rad;
    wheel_leg_U.roll_rate_rad_s    = gyro_roll_rad_s;
    wheel_leg_U.yaw_rad            = imu_yaw_rad;
    wheel_leg_U.yaw_rate_rad_s     = gyro_yaw_rad_s;
    wheel_leg_U.distance_m         = chassis_distance_m;
    wheel_leg_U.velocity_m_s       = chassis_velocity_m_s;

    wheel_leg_U.joint_angle_rad[0] = left_back_angle_rad;
    wheel_leg_U.joint_angle_rad[1] = left_front_angle_rad;
    wheel_leg_U.joint_angle_rad[2] = right_back_angle_rad;
    wheel_leg_U.joint_angle_rad[3] = right_front_angle_rad;

    wheel_leg_U.joint_rate_rad_s[0] = left_back_rate_rad_s;
    wheel_leg_U.joint_rate_rad_s[1] = left_front_rate_rad_s;
    wheel_leg_U.joint_rate_rad_s[2] = right_back_rate_rad_s;
    wheel_leg_U.joint_rate_rad_s[3] = right_front_rate_rad_s;

    wheel_leg_U.normal_force_n[0] = left_normal_force_n;
    wheel_leg_U.normal_force_n[1] = right_normal_force_n;
    wheel_leg_U.time_s             = system_time_s;

    /* 2. 填入目标，不是在这里填写最终电机力矩。 */
    wheel_leg_U.velocity_command_m_s  = target_velocity_m_s;
    wheel_leg_U.yaw_rate_command_rad_s = target_yaw_rate_rad_s;
    wheel_leg_U.leg_length_command_m   = target_leg_length_m;
    wheel_leg_U.jump_command           = jump_requested;
    wheel_leg_U.zero_force_command     = emergency_zero_force;

    /* 3. 执行且只执行一个控制周期。 */
    wheel_leg_step();

    /* 4. 把模型输出的 Nm 力矩交给你的电机控制器。 */
    Motor_SetTorqueNm(LEFT_WHEEL,  wheel_leg_Y.wheel_torque_nm[0]);
    Motor_SetTorqueNm(RIGHT_WHEEL, wheel_leg_Y.wheel_torque_nm[1]);
    Motor_SetTorqueNm(LEFT_BACK,   wheel_leg_Y.joint_torque_nm[0]);
    Motor_SetTorqueNm(LEFT_FRONT,  wheel_leg_Y.joint_torque_nm[1]);
    Motor_SetTorqueNm(RIGHT_BACK,  wheel_leg_Y.joint_torque_nm[2]);
    Motor_SetTorqueNm(RIGHT_FRONT, wheel_leg_Y.joint_torque_nm[3]);
}
```

停止模块时可以调用：

```c
wheel_leg_terminate();
```

## 3. 六路力矩映射

本包是 **@LEG_VARIANT@** 独立版本，只包含这一种腿型的运动学和 VMC，不包含另一腿型的分支或代码。对外仍保持左右轮与四个关节的六路力矩接口。

| 生成代码输出 | 含义 | 单位 |
|---|---|---:|
| `wheel_leg_Y.wheel_torque_nm[0]` | 左轮目标力矩 | Nm |
| `wheel_leg_Y.wheel_torque_nm[1]` | 右轮目标力矩 | Nm |
| `wheel_leg_Y.joint_torque_nm[0]` | 左后关节目标力矩 | Nm |
| `wheel_leg_Y.joint_torque_nm[1]` | 左前关节目标力矩 | Nm |
| `wheel_leg_Y.joint_torque_nm[2]` | 右后关节目标力矩 | Nm |
| `wheel_leg_Y.joint_torque_nm[3]` | 右前关节目标力矩 | Nm |

如果电机驱动接收电流而不是 Nm，换算只能放在硬件适配层，不要写进模型核心：

```c
float TorqueNmToCurrentA(float torque_nm)
{
    return torque_nm / (MOTOR_KT_NM_PER_A * REDUCTION_RATIO * TRANSMISSION_EFFICIENCY);
}
```

必须根据实物标定电机力矩常数、减速比、效率、方向和零位。不要直接把 Nm 数值当作电流发送。

## 4. 接入你自己的 PID 结构体

只修改下面两个用户文件：

```text
include/wheel_leg_user_types.h
src/wheel_leg_user.c
```

它们在同一目录重复导出时会被保留。生成代码本身不提供 PID 算法，只提供以下统一端口：

```c
typedef float (*WheelLeg_PIDCalculateFn)(void *instance,
                                         float measure,
                                         float reference);
typedef void (*WheelLeg_PIDResetFn)(void *instance);
```

这使你的 PID 结构体可以保持原样。以 `balance_chassis-main` 的 `PIDInstance`、`PIDInit()`、`PIDCalculate()` 为例，在你的嵌入式工程适配文件中写：

```c
#include "wheel_leg.h"
#include "controller.h"  /* 你自己的 PIDInstance/PIDCalculate */

static PIDInstance position_pid;
static PIDInstance roll_pid;

static float AppPIDCalculate(void *instance,float measure,float reference)
{
    return PIDCalculate((PIDInstance *)instance,measure,reference);
}

static void AppPIDReset(void *instance)
{
    PIDInstance *pid=(PIDInstance *)instance;
    pid->Iout=0.0f;
    pid->ITerm=0.0f;
    pid->Last_Err=0.0f;
    pid->Last_Output=0.0f;
}

void ChassisControlInit(void)
{
    PID_Init_Config_s position_config={
        .Kp=2.0f,.Ki=0.2f,.Kd=0.05f,.MaxOut=1.5f,
        .IntegralLimit=0.5f,
        .Improve=PID_Trapezoid_Intergral|PID_Integral_Limit,
    };
    PID_Init_Config_s roll_config={
        .Kp=10.0f,.Ki=0.0f,.Kd=0.5f,.MaxOut=5.0f,
        .Improve=PID_Derivative_On_Measurement|PID_DerivativeFilter,
        .Derivative_LPF_RC=0.01f,
    };
    wheel_leg_initialize();
    PIDInit(&position_pid,&position_config);
    PIDInit(&roll_pid,&roll_config);
    wheel_leg_bind_pid(0u,&position_pid,AppPIDCalculate,AppPIDReset);
    wheel_leg_bind_pid(1u,&roll_pid,AppPIDCalculate,AppPIDReset);
}
```

如果你以后换另一套 PID，只需重写 `AppPIDCalculate()` 的这一层类型转换，生成代码不变。

端口和生成控制环对应关系：

| 端口 | 宏 | 调用参数 `(measure, reference)` |
|---:|---|---|
| 0 | `WLC_PID_LEFT_LENGTH` | 左腿实际长度、目标长度；输出腿速目标 |
| 1 | `WLC_PID_LEFT_SPEED` | 左腿实际伸缩速度、腿速目标；输出支撑力修正 |
| 2 | `WLC_PID_RIGHT_LENGTH` | 右腿实际长度、目标长度；输出腿速目标 |
| 3 | `WLC_PID_RIGHT_SPEED` | 右腿实际伸缩速度、腿速目标；输出支撑力修正 |
| 4 | `WLC_PID_ROLL` | 实际横滚角、0；输出左右腿支撑力差 |
| 5 | `WLC_PID_YAW_ANGLE` | 实际航向角、目标航向角；输出航向角速度目标 |
| 6 | `WLC_PID_YAW_RATE` | 实际航向角速度、目标角速度；输出差速转向力矩 |
| 7 | `WLC_PID_ANTI_SPLIT` | 左右虚拟腿角之差、0；输出抗劈叉髋力矩 |

你可以只绑定需要替换的控制环。没有绑定的端口继续使用生成核心的默认回退计算，因此可以逐个 PID 验证，不要求一次改完。

### 4.1 PID 放在目标输入前

例如用位置 PID 产生速度目标，在 `WheelLeg_UserBeforeStep()` 中写：

```c
void WheelLeg_UserBeforeStep(ExtU_wheel_leg_T *u,
                             const P_wheel_leg_T *p,
                             DW_wheel_leg_T *dw)
{
    const float target_position_m = p->user.parameter[0];
    (void)dw;
    u->velocity_command_m_s = wheel_leg_call_pid(
        0u,u->distance_m,target_position_m);
}
```

### 4.2 PID 叠加到最终力矩

例如增加横滚 PID，在 `WheelLeg_UserAfterControl()` 中写：

```c
void WheelLeg_UserAfterControl(const ExtU_wheel_leg_T *u,
                               const B_wheel_leg_T *b,
                               const P_wheel_leg_T *p,
                               DW_wheel_leg_T *dw,
                               ExtY_wheel_leg_T *y)
{
    float correction;
    (void)b;
    (void)p;(void)dw;
    correction = wheel_leg_call_pid(1u,u->roll_rad,0.0f);

    y->joint_torque_nm[0] += correction;
    y->joint_torque_nm[1] += correction;
    y->joint_torque_nm[2] -= correction;
    y->joint_torque_nm[3] -= correction;

    /* 自定义叠加后必须再次执行最终力矩限幅。 */
}
```

默认预留端口 `0`～`7`，但 PID 实例及其积分、滤波、DWT 和故障状态全部保存在你自己的 `PIDInstance` 中。生成代码只保存实例指针和调用函数，不复制 PID 状态。

## 5. 中间信号在哪里读取

`wheel_leg_B` 对应 Simulink 生成代码中的 block signals：

```c
wheel_leg_B.leg_length_m[2];
wheel_leg_B.virtual_leg_angle_rad[2];
wheel_leg_B.leg_rate_m_s[2];
wheel_leg_B.virtual_leg_rate_rad_s[2];
wheel_leg_B.support_force_n[2];
wheel_leg_B.virtual_hip_torque_nm[2];
wheel_leg_B.target_velocity_m_s;
wheel_leg_B.target_distance_m;
wheel_leg_B.target_yaw_rad;
```

自定义控制优先读取这些明确的中间信号，不要访问 `wheel_leg_DW.core` 内部数组。

## 6. 调用周期和保护

- `wheel_leg_step()` 必须按生成参数中的固定周期调用；默认是 0.001 s。
- 输入角度全部为 rad，角速度为 rad/s，长度为 m，速度为 m/s，力为 N，力矩为 Nm。
- 电机方向与数组映射必须先在拆载、小电流状态逐个确认。
- 应用层必须另外实现 CAN/传感器超时、看门狗、物理急停和掉线归零。
- 自定义 PID 修改最终力矩后必须重新限幅，并建议增加力矩变化率限制。
- 第一次实物测试必须使用保护架、低力矩和可切断电源的急停。

## 7. 编译文件

将以下源文件加入新的嵌入式工程：

```text
src/wheel_leg.c
src/wheel_leg_user.c
src/wlc_internal.c
```

增加头文件搜索路径：

```text
include/
generated/
```

核心只依赖标准 C 数学函数。若工具链需要，需要链接 `libm`；ARM GCC 通常在链接选项中加入 `-lm`。
'''

CMAKE='''cmake_minimum_required(VERSION 3.16)
project(wheelleg_control C)
add_library(wheel_leg STATIC src/wlc_internal.c src/wheel_leg.c src/wheel_leg_user.c)
target_include_directories(wheel_leg PUBLIC include generated)
target_compile_features(wheel_leg PUBLIC c_std_11)
add_executable(wlc_self_test tests/test_runner.c)
target_link_libraries(wlc_self_test PRIVATE wheel_leg m)
enable_testing()
add_test(NAME wlc_self_test COMMAND wlc_self_test)
'''


def _audit(files):
    banned=('#include "stm32','#include "FreeRTOS','#include "cmsis','HAL_','pvPortMalloc','malloc(','calloc(','realloc(','Python.h','mujoco')
    findings=[]
    for path in files:
        text=path.read_text(encoding='utf-8')
        for token in banned:
            if token in text:findings.append(f'{path.name}: {token}')
    if findings:raise RuntimeError('检测到禁止依赖：'+'; '.join(findings))


def export_package(directory,profile='wheelleg-reference',lqr=None,mpc=None,sample_time=.001,compiler='gcc',parameters=None):
    directory=Path(directory).resolve();profile=_identifier(profile)
    values=dict(DEFAULT_PARAMETERS);values['sample_time_s']=sample_time
    if parameters:values.update(parameters)
    numeric=[v for key,v in values.items() if key!='leg_topology']
    if not all(np.isfinite(v) and v>0 for v in numeric):raise ValueError('生产参数必须全部为有限正数')
    if int(values['leg_topology']) not in (0,1):raise ValueError('腿型必须是五连杆(0)或串联腿(1)')
    serial=int(values['leg_topology'])==1
    variant='serial_leg' if serial else 'five_bar'
    variant_cn='二关节串联腿' if serial else '并联五连杆'
    if not .0001<=values['sample_time_s']<=.01:raise ValueError('控制周期必须在 0.0001–0.01 s')
    if not .09<=values['min_leg_length_m']<values['max_leg_length_m']<=.39:raise ValueError('腿长需满足 0.09 <= 最短 < 最长 <= 0.39 m')
    lqr=np.asarray(DEFAULT_LQR if lqr is None else lqr,dtype=float);mpc=np.asarray(DEFAULT_MPC if mpc is None else mpc,dtype=float)
    if lqr.shape!=(12,4) or mpc.shape!=(12,4) or not np.isfinite(np.r_[lqr.ravel(),mpc.ravel()]).all():raise ValueError('LQR/MPC 系数必须为有限的 12×4 数组')
    if directory==ROOT or ROOT in directory.parents and directory.name in ('controller','simulation','portable_control'):
        raise ValueError('请选择独立导出目录，不能覆盖工程源码目录')
    for folder in ('include','src','generated','examples','tests','build','LICENSES'):(directory/folder).mkdir(parents=True,exist_ok=True)
    # Remove the filename used by exporter v1.  Preserve wheel_leg_user.c so a
    # deliberate re-export never destroys application PID/custom control code.
    for legacy in (directory/'src'/'wlc.c',directory/'src'/'wheel_leg_pid.c',directory/'include'/'wheel_leg_pid.h'):
        if legacy.exists():legacy.unlink()
    shutil.copy2(ROOT/'portable_control'/'wlc.h',directory/'include'/'wlc.h')
    shutil.copy2(ROOT/'portable_control'/'wlc.c',directory/'src'/'wlc_internal.c')
    shutil.copy2(ROOT/'portable_control'/'kinematics'/('serial_leg.h' if serial else 'five_bar.h'),directory/'src'/'wlc_kinematics.h')
    for source in (ROOT/'portable_control'/'model').iterdir():
        target=directory/('include' if source.suffix=='.h' else 'src')/source.name
        preserved=source.name in ('wheel_leg_user.c','wheel_leg_user_types.h')
        legacy_user=False
        if preserved and target.exists():
            old=target.read_text(encoding='utf-8')
            legacy_user=('wheel_leg_pid.h' in old or 'WheelLeg_PID_Reset' in old or
                         'WheelLeg_PID_Step' in old or 'WheelLeg_PIDPort pid' in old)
            if legacy_user:shutil.copy2(target,target.with_suffix(target.suffix+'.pre_pid_interface.bak'))
        if not preserved or not target.exists() or legacy_user:shutil.copy2(source,target)
    (directory/'generated'/'wlc_generated_params.h').write_text(generated_header(profile,lqr,mpc,values),encoding='utf-8')
    joints=('wheel_leg_U.joint_angle_rad[0]=wheel_leg_U.joint_angle_rad[2]=-1.7148122f;\n'
            '    wheel_leg_U.joint_angle_rad[1]=wheel_leg_U.joint_angle_rad[3]=2.3051922f;' if serial else
            'wheel_leg_U.joint_angle_rad[0]=wheel_leg_U.joint_angle_rad[2]=2.8857736f;\n'
            '    wheel_leg_U.joint_angle_rad[1]=wheel_leg_U.joint_angle_rad[3]=0.2558225f;')
    (directory/'tests'/'test_runner.c').write_text(TEST_RUNNER.replace('@JOINT_INITIALIZATION@',joints),encoding='utf-8')
    (directory/'examples'/'baremetal_adapter.c').write_text(BAREMETAL,encoding='utf-8')
    (directory/'examples'/'freertos_adapter.c').write_text(FREERTOS,encoding='utf-8')
    (directory/'README.md').write_text(README,encoding='utf-8')
    (directory/'INTEGRATION_GUIDE_CN.md').write_text(INTEGRATION_GUIDE_CN.replace('@LEG_VARIANT@',variant_cn),encoding='utf-8')
    (directory/'CMakeLists.txt').write_text(CMAKE,encoding='utf-8')
    shutil.copy2(ROOT/'balance_chassis-main'/'LICENSE',directory/'LICENSES'/'NeoZng-MIT.txt')
    sources=list((directory/'include').glob('*.h'))+list((directory/'src').glob('*.[ch]'))+[directory/'generated'/'wlc_generated_params.h']
    _audit(sources)
    compiler_path=shutil.which(compiler)
    if not compiler_path:raise RuntimeError(f'找不到 C 编译器：{compiler}')
    executable=directory/'build'/('wlc_self_test.exe' if __import__('os').name=='nt' else 'wlc_self_test')
    command=[compiler_path,'-std=c11','-O2','-Wall','-Wextra','-Werror','-pedantic','-I'+str(directory/'include'),'-I'+str(directory/'generated')]
    command += [str(path) for path in sorted((directory/'src').glob('*.c'))]
    command += [str(directory/'tests'/'test_runner.c'),'-lm','-o',str(executable)]
    built=subprocess.run(command,capture_output=True,text=True,timeout=60)
    if built.returncode:raise RuntimeError('导出包独立编译失败：\n'+built.stdout+built.stderr)
    tested=subprocess.run([str(executable)],capture_output=True,text=True,timeout=20)
    if tested.returncode:raise RuntimeError('导出包自测失败：\n'+tested.stdout+tested.stderr)
    artifacts=sources+[directory/'README.md',directory/'INTEGRATION_GUIDE_CN.md',directory/'CMakeLists.txt',
                       directory/'tests'/'test_runner.c',directory/'examples'/'baremetal_adapter.c',directory/'examples'/'freertos_adapter.c']
    hashes={str(p.relative_to(directory)).replace('\\','/'):hashlib.sha256(p.read_bytes()).hexdigest() for p in artifacts}
    parameter_bytes=(directory/'generated'/'wlc_generated_params.h').read_bytes()
    manifest=dict(schema_version=3,api_version=2,profile=profile,leg_variant=variant,generated_at=datetime.now(timezone.utc).isoformat(),sample_time_s=values['sample_time_s'],parameters=values,
                  float_format='IEEE-754 float32',dynamic_allocation=False,external_runtime_dependencies=[],parameter_sha256=hashlib.sha256(parameter_bytes).hexdigest(),
                  compiler=compiler_path,self_test=tested.stdout.strip(),files=hashes)
    (directory/'manifest.json').write_text(json.dumps(manifest,indent=2,ensure_ascii=False),encoding='utf-8')
    return manifest
