/* Generated by python -m simulation.design_lqr. Rebuild after changes. */
#ifndef LQR_GAINS_H
#define LQR_GAINS_H
#define LQR_DEFAULT_K {-1.397455977e+01f, -1.888491386e+01f, -1.758591791e+02f, -2.351462099e+01f}
#define LQR_OUTPUT_LIMIT 4.000000000e+01f
#define LQR_SAMPLE_TIME 1.000000000e-03f
#define LQR_DESIGN_ID "33e0ec599b072190aacb45db9a13c80258f48ba13de52e88cd42c292f15ff180"
#endif
